name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v6
        with:
          ref: "dev"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: task deps

      - name: update
        run: task update

      - name: Open Pull Request to update dependencies
        uses: peter-evans/create-pull-request@v8
        id: cpr
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: "update-dependencies"
          title: "Update dependencies"
          body: "Dependecy update"
          base: "dev"
          commit-message: "Update dependencies"
          delete-branch: true

      - name: Enable Pull Request Automerge and delete if all checks pass
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --delete-branch --merge "$PR_URL"
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Step summary
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "### Updated dependencies :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
